---
- hosts: localhost
  connection: local
  name: Get Installed Firmware Inventory
  gather_facts: no
  collections:
    - dellemc.openmanage
  vars:
    idrac_ip: 10.0.0.89
    idrac_user: root
    idrac_password: r0gerwilc0

  tasks:
    # Precheck: Validate IP Address
  - name: Ensure idrac_ip is defined and is a valid IP address.
    ansible.builtin.assert:
      that:
        - idrac_ip is defined
        - idrac_ip is match("^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$")
      fail_msg: "'idrac_ip' must be defined and be a valid IP address."

    # Precheck: Validate Username and Password
  - name: Ensure idrac_user and idrac_password are defined.
    ansible.builtin.assert:
      that:
        - idrac_user is defined
        - idrac_password is defined
      fail_msg: "'idrac_user' and 'idrac_password' must be defined."

  - name: Get Installed Firmware Inventory.
    idrac_firmware_info:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      validate_certs: False
    register: results

    # print to screen
  - name: Display the gathered facts about Firmware
    debug:
      var: results

    # Precheck: Ensure results.firmware_info.Firmware exists and is a list
  - name: Ensure results.firmware_info.Firmware exists and is a list.
    ansible.builtin.assert:
      that:
        - results.firmware_info.Firmware is defined
        - results.firmware_info.Firmware is iterable
      fail_msg: "'results.firmware_info.Firmware' must exist and be a list."

  - name: Display just the results.firmware_info.Firmware[]ElementNames
    debug:
      var: item.ElementName
    loop: "{{ results.firmware_info.Firmware }}"

